apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: must-gather-operator
subjects:
- kind: ServiceAccount
  name: must-gather-operator
  namespace: must-gather-operator
roleRef:
  kind: ClusterRole
  name: must-gather-operator
  apiGroup: rbac.authorization.k8s.io
